[package]
name = "id3-decoder"
version = "0.1.0"
authors = ["SaiintBrisson <luizcarlosmpc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
bytes = "1.0.1"
encoding_rs = "0.8.28"
